PATH_TO_DATA: "/Users/adithyamurali/dev/DeepMilestones/jigsaws/0101_video/"
PATH_TO_CLUSTERING_RESULTS: "/Users/adithyamurali/dev/DeepMilestones/clustering/clustering_0101/"
PATH_TO_KINEMATICS: "/Users/adithyamurali/dev/DeepMilestones/jigsaws/0101_kinematics/"
CONFIG_FILE: "meta_file_0101.txt"
ALEXNET_FEATURES_FOLDER : "alexnetfeatures/"
VGG_FEATURES_FOLDER : "vggfeatures/"
PROC_FEATURES_FOLDER : "features/"
REMOTE : True
SIMULATION : True
KINEMATICS_DIM : 3
CROP_PARAMS_CAPTURE_1: "crop=330:260:200:170"
CROP_PARAMS_CAPTURE_2: "crop=330:260:150:150"
CAMERA: "capture1"
SR: 1
PRUNING_FACTOR: 0.5
N_COMPONENTS_CP : 50
N_COMPONENTS_L1 : 10
N_COMPONENTS_L2 : 3
N_COMPONENTS_CP_KIN : 50
N_COMPONENTS_L1_KIN : 10
