PATH_TO_DATA: "/Users/adithyamurali/dev/DeepMilestones/jigsaws/1000_video/"
PATH_TO_CLUSTERING_RESULTS: "/Users/adithyamurali/dev/DeepMilestones/clustering/clustering_1000/"
PATH_TO_KINEMATICS: "/Users/adithyamurali/dev/DeepMilestones/jigsaws/1000_kinematics/"
CONFIG_FILE: "meta_file_1000.txt"
ALEXNET_FEATURES_FOLDER : "alexnetfeatures/"
VGG_FEATURES_FOLDER : "vggfeatures/"
PROC_FEATURES_FOLDER : "features/"
REMOTE : True
SIMULATION : True
KINEMATICS_DIM : 3
CROP_PARAMS_CAPTURE_1: "crop=330:260:200:170"
CROP_PARAMS_CAPTURE_2: "crop=330:260:150:150"
CAMERA: "capture1"
SR: 1
PRUNING_FACTOR: 0.25
N_COMPONENTS_CP : 20
N_COMPONENTS_L1 : 2
N_COMPONENTS_L2 : 2
N_COMPONENTS_CP_KIN : 20
N_COMPONENTS_L1_KIN : 2
