PATH_TO_DATA: "/home/animesh/DeepMilestones/jigsaws/Suturing_video/"
PATH_TO_CLUSTERING_RESULTS: "/home/animesh/DeepMilestones/clustering_E12345/"
PATH_TO_KINEMATICS: "/home/animesh/DeepMilestones/jigsaws/Suturing_kinematics/kinematics/AllGestures/"
CONFIG_FILE: "meta_file_Suturing.txt"
ALEXNET_FEATURES_FOLDER : "alexnetfeatures_2/"
VGG_FEATURES_FOLDER : "vggfeatures_2/"
PROC_FEATURES_FOLDER : "features_E12345/"
CROP_PARAMS_CAPTURE_1: "crop=330:260:200:170"
CROP_PARAMS_CAPTURE_2: "crop=330:260:150:150"
SR: 3
PRUNING_FACTOR: 0.8