PATH_TO_DATA: "/Users/animesh/work/DeepMilestones/jigsaws/Suturing_video/"
PATH_TO_CLUSTERING_RESULTS: "/Users/animesh/work/DeepMilestones/clustering/clustering_suturing/"
PATH_TO_KINEMATICS: "/Users/animesh/work/DeepMilestones/jigsaws/Suturing_kinematics/kinematics/AllGestures/"
CONFIG_FILE: "meta_file_Suturing.txt"
ALEXNET_FEATURES_FOLDER : "alexnetfeatures_2/"
VGG_FEATURES_FOLDER : "vggfeatures_2/"
PROC_FEATURES_FOLDER : "features_E12345/"
REMOTE : True
SIMULATION : False
KINEMATICS_DIM : 38
CROP_PARAMS_CAPTURE_1: "crop=330:260:200:170"
CROP_PARAMS_CAPTURE_2: "crop=330:260:150:150"
CAMERA: "capture2"
SR: 3
PRUNING_FACTOR: 0.75
N_COMPONENTS_CP : 50
N_COMPONENTS_L1 : 10
N_COMPONENTS_L2 : 3